<?php
declare(strict_types=1);

require_once __DIR__ . '/../app/_modulo.php';

moduloCrud(
    'Cobranzas',
    'cobranzas',
    'controllers/ventas/cobranza_controller.php',
    ['id_cobranza' => 'ID', 'con_numero' => 'Contrato', 'pagador_nombre' => 'Pagó', 'fecha' => 'Fecha', 'monto_total' => 'Monto', 'estado' => 'Estado'],
    '<input type="hidden" name="accion" value="registrar"><input type="hidden" name="detalles" data-detalles-json><input type="hidden" name="id_contrato" data-cobranza-contrato required><div class="form-grid cobranza-grid"><label class="wide">Buscar contrato<div class="catalog-search cobranza-contract-search"><input data-cobranza-buscar placeholder="N° de contrato, DNI o apellidos" autocomplete="off"><div class="buscador-resultados" data-cobranza-resultados hidden></div><div class="catalog-selected" data-cobranza-selected hidden><span></span><button type="button" data-cobranza-clear aria-label="Quitar contrato">×</button></div></div></label><button class="secondary align-end" type="button" data-cargar-hitos>Cargar cuotas</button><label>Fecha<input name="fecha" type="datetime-local" required></label><label>Medio<select name="medio_pago"><option selected>EFECTIVO</option><option>TRANSFERENCIA</option><option>YAPE</option><option>PLIN</option><option>TARJETA</option></select></label><label data-pagador-grupal hidden>Quién realiza el pago<select name="id_cliente_pagador"></select></label><div class="comprobante-fields wide" data-comprobante-campos><label>N° de operación<input name="numero_operacion"></label><label>Voucher (PDF, JPG o PNG, hasta 5 MiB)<input name="voucher" type="file" accept=".pdf,image/jpeg,image/png"></label></div></div><section class="line-editor"><div class="editor-heading"><div><strong>Aplicación del pago</strong><span>Seleccione una o más cuotas y especifique el monto.</span></div></div><div data-hitos-cobranza><p class="hint">Busca y selecciona un contrato para consultar sus cuotas pendientes.</p></div></section>',
    'Registra pagos parciales o completos, con comprobante validado.',
    ['id'=>'id_cobranza','sinEdicion'=>true,'anulacion'=>true,'voucher'=>true,'grupo'=>'VENTAS','formularioTitulo'=>'Registrar pago','metricas'=>[['label'=>'Cobrado','type'=>'sum','field'=>'monto_total','state'=>'REGISTRADO','currency'=>true,'color'=>'accent-green'],['label'=>'Operaciones','type'=>'count','state'=>'REGISTRADO','color'=>'accent-blue'],['label'=>'Anuladas','type'=>'count','state'=>'ANULADO','color'=>'accent-purple']],'filtros'=>'<form data-filter-form class="filter-grid"><label>Desde<input name="fecha_inicio" type="date"></label><label>Hasta<input name="fecha_fin" type="date"></label><label>Estado<select name="estado"><option value="">Todos</option><option>REGISTRADO</option><option>ANULADO</option></select></label><button class="secondary" type="submit">Filtrar</button><button class="secondary outline" type="button" data-filter-clear>Limpiar</button></form>','scripts'=>['resources/js/componentes/buscador_catalogo.js','resources/js/cobranzas.js']]
);
