<?php
declare(strict_types=1);
require_once __DIR__.'/../app/_modulo.php';
moduloCrud(
    'Usuarios y permisos', 'usuarios', 'controllers/rrhh/usuario_controller.php',
    ['usu_nombre'=>'Usuario','nombre'=>'Persona','cargo'=>'Cargo','usu_estado'=>'Estado'],
    '<input type="hidden" name="accion" value="guardar"><input type="hidden" name="id_usuario" value="0"><div class="form-grid"><label>Persona<select name="id_personal" data-persona-select required><option value="">Cargando personal…</option></select></label><label>Usuario<input name="usuario" required></label><label>Contraseña inicial o nueva<input name="clave" type="password" minlength="12" autocomplete="new-password"></label><label>Estado<select name="estado"><option value="1">Activo</option><option value="0">Inactivo</option></select></label></div>',
    'Cuentas de acceso y permisos de navegación.',
    ['id'=>'id_usuario','grupo'=>'ADMINISTRACIÓN','scripts'=>['resources/js/usuarios.js','resources/js/permisos.js'],'complementoPermiso'=>'administrar',
     'complemento'=>'<section class="permission-grid" data-permission-panel data-controller="'.tessaBase().'controllers/rrhh/usuario_controller.php"><article class="panel permission-note"><p class="eyebrow">PLANTILLA DEL CARGO</p><h3>Permisos por cargo</h3><p class="muted">Elija Habilitado o Deshabilitado junto a cada acción; el cambio se guarda automáticamente. «Ver» controla el acceso y la visibilidad del menú.</p><form data-cargo-permission><label>Cargo<select name="id_cargo" data-cargo-options required></select></label><label hidden>Permiso<select name="id_permiso" data-permission-options required></select></label><label hidden>Acceso<select name="permitido"><option value="1">Permitir</option><option value="0">Denegar</option></select></label><button class="secondary" type="submit" hidden>Actualizar plantilla</button><p data-permission-message role="status"></p></form></article><article class="panel permission-note"><p class="eyebrow">EXCEPCIÓN INDIVIDUAL</p><h3>Permisos por persona</h3><p class="muted">Elija Habilitado, Deshabilitado o Heredar cargo junto a cada acción. La excepción individual prevalece sobre el cargo.</p><form data-person-permission><label>Personal<select name="id_personal" data-person-options required></select></label><label hidden>Permiso<select name="id_permiso" data-permission-options required></select></label><label hidden>Acceso<select name="permitido"><option value="1">Permitir adicional</option><option value="0">Denegar</option></select></label><button class="secondary" type="submit" hidden>Guardar excepción</button><p data-permission-message role="status"></p></form></article></section>']
); ?>
