-- Ejecutar una vez sobre una instalación existente. No elimina ni importa registros.
USE tessa_control_pagos;
ALTER TABLE cliente ADD COLUMN apellidos VARCHAR(150) NULL AFTER nombres;
DELIMITER $$
DROP PROCEDURE IF EXISTS sp_cliente_guardar$$
CREATE PROCEDURE sp_cliente_guardar(IN p_id INT UNSIGNED,IN p_tipo VARCHAR(10),IN p_doc VARCHAR(11),IN p_nombres VARCHAR(150),IN p_apellidos VARCHAR(150),IN p_razon VARCHAR(180),IN p_correo VARCHAR(160),IN p_telefono VARCHAR(30),IN p_direccion VARCHAR(220),IN p_estado TINYINT) BEGIN IF p_id=0 THEN INSERT INTO cliente(tipo,documento,nombres,apellidos,razon_social,correo,telefono,direccion,estado) VALUES(p_tipo,p_doc,NULLIF(p_nombres,''),NULLIF(p_apellidos,''),NULLIF(p_razon,''),NULLIF(p_correo,''),NULLIF(p_telefono,''),NULLIF(p_direccion,''),p_estado); SET p_id=LAST_INSERT_ID(); ELSE UPDATE cliente SET tipo=p_tipo,documento=p_doc,nombres=NULLIF(p_nombres,''),apellidos=NULLIF(p_apellidos,''),razon_social=NULLIF(p_razon,''),correo=NULLIF(p_correo,''),telefono=NULLIF(p_telefono,''),direccion=NULLIF(p_direccion,''),estado=p_estado WHERE id_cliente=p_id; END IF; SELECT 1 resultado,'Cliente guardado.' mensaje,p_id id_cliente; END$$
DROP PROCEDURE IF EXISTS sp_cliente_buscar$$
CREATE PROCEDURE sp_cliente_buscar(IN p_consulta VARCHAR(100)) BEGIN SELECT id_cliente,tipo,documento,nombres,apellidos,razon_social,estado FROM cliente WHERE estado=1 AND (documento LIKE CONCAT('%',p_consulta,'%') OR nombres LIKE CONCAT('%',p_consulta,'%') OR apellidos LIKE CONCAT('%',p_consulta,'%') OR CONCAT_WS(' ',nombres,apellidos) LIKE CONCAT('%',p_consulta,'%') OR razon_social LIKE CONCAT('%',p_consulta,'%')) ORDER BY CASE WHEN documento=p_consulta THEN 0 ELSE 1 END,documento LIMIT 20; END$$
DROP PROCEDURE IF EXISTS sp_contrato_listar$$
CREATE PROCEDURE sp_contrato_listar() BEGIN SELECT c.*,COALESCE(SUM(h.monto-h.monto_pagado),0) saldo,COALESCE(cl.razon_social,CONCAT_WS(' ',cl.nombres,cl.apellidos)) cliente_nombre,s.nombre servicio_nombre FROM contrato c JOIN cliente cl ON cl.id_cliente=c.id_cliente JOIN servicio s ON s.id_servicio=c.id_servicio LEFT JOIN contrato_hito h ON h.id_contrato=c.id_contrato AND h.estado<>'ANULADO' GROUP BY c.id_contrato ORDER BY c.id_contrato DESC; END$$
DROP PROCEDURE IF EXISTS sp_dashboard_ventas_pendientes$$
CREATE PROCEDURE sp_dashboard_ventas_pendientes(IN p_desde DATE,IN p_hasta DATE) BEGIN SELECT h.id_hito,c.con_numero,COALESCE(cl.razon_social,CONCAT_WS(' ',cl.nombres,cl.apellidos)) cliente,h.descripcion,h.fecha_vencimiento,h.monto-h.monto_pagado saldo,h.estado FROM contrato_hito h JOIN contrato c ON c.id_contrato=h.id_contrato JOIN cliente cl ON cl.id_cliente=c.id_cliente WHERE c.estado='ACTIVO' AND h.estado IN('PENDIENTE','PARCIAL','VENCIDO') AND h.fecha_vencimiento BETWEEN p_desde AND p_hasta ORDER BY h.fecha_vencimiento,h.id_hito LIMIT 30; END$$
DELIMITER ;
