CREATE DATABASE IF NOT EXISTS tessa_control_pagos CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tessa_control_pagos;

CREATE TABLE modulo (id_modulo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,codigo VARCHAR(40) NOT NULL UNIQUE,nombre VARCHAR(80) NOT NULL) ENGINE=InnoDB;
CREATE TABLE permiso (id_permiso INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,id_modulo INT UNSIGNED NOT NULL,accion ENUM('ver','crear','editar','anular','administrar') NOT NULL,UNIQUE KEY uq_permiso(id_modulo,accion),FOREIGN KEY(id_modulo) REFERENCES modulo(id_modulo)) ENGINE=InnoDB;
CREATE TABLE cargo (id_cargo INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(100) NOT NULL UNIQUE,estado TINYINT NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE personal (id_personal INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,dni CHAR(8) NOT NULL UNIQUE,nombres VARCHAR(120) NOT NULL,apellidos VARCHAR(120) NOT NULL,correo VARCHAR(160) NULL,telefono VARCHAR(30) NULL,id_cargo INT UNSIGNED NOT NULL,estado TINYINT NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(id_cargo) REFERENCES cargo(id_cargo)) ENGINE=InnoDB;
CREATE TABLE usuario (id_usuario INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,id_personal INT UNSIGNED NOT NULL UNIQUE,usu_nombre VARCHAR(80) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,usu_estado TINYINT NOT NULL DEFAULT 1,failed_attempts TINYINT UNSIGNED NOT NULL DEFAULT 0,failed_window_started DATETIME NULL,locked_until DATETIME NULL,ultimo_login DATETIME NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(id_personal) REFERENCES personal(id_personal)) ENGINE=InnoDB;
CREATE TABLE cargo_permiso (id_cargo INT UNSIGNED NOT NULL,id_permiso INT UNSIGNED NOT NULL,permitido TINYINT NOT NULL DEFAULT 1,PRIMARY KEY(id_cargo,id_permiso),FOREIGN KEY(id_cargo) REFERENCES cargo(id_cargo),FOREIGN KEY(id_permiso) REFERENCES permiso(id_permiso)) ENGINE=InnoDB;
CREATE TABLE persona_permiso (id_personal INT UNSIGNED NOT NULL,id_permiso INT UNSIGNED NOT NULL,permitido TINYINT NOT NULL,PRIMARY KEY(id_personal,id_permiso),FOREIGN KEY(id_personal) REFERENCES personal(id_personal),FOREIGN KEY(id_permiso) REFERENCES permiso(id_permiso)) ENGINE=InnoDB;
CREATE TABLE cliente (id_cliente INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,tipo ENUM('NATURAL','JURIDICA') NOT NULL,documento VARCHAR(11) NOT NULL UNIQUE,nombres VARCHAR(150) NULL,apellidos VARCHAR(150) NULL,razon_social VARCHAR(180) NULL,correo VARCHAR(160) NULL,telefono VARCHAR(30) NULL,direccion VARCHAR(220) NULL,estado TINYINT NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE servicio (id_servicio INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,nombre VARCHAR(150) NOT NULL UNIQUE,descripcion VARCHAR(500) NULL,precio_referencia DECIMAL(12,2) NOT NULL DEFAULT 0,estado TINYINT NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE contrato (id_contrato INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,con_numero VARCHAR(30) NOT NULL UNIQUE,id_cliente INT UNSIGNED NOT NULL,id_servicio INT UNSIGNED NOT NULL,id_responsable INT UNSIGNED NOT NULL,tipo ENUM('INDIVIDUAL','GRUPAL') NOT NULL,fecha DATE NOT NULL,monto_bruto DECIMAL(12,2) NOT NULL,descuento DECIMAL(12,2) NOT NULL DEFAULT 0,monto_neto DECIMAL(12,2) NOT NULL,estado ENUM('BORRADOR','ACTIVO','FINALIZADO','ANULADO') NOT NULL DEFAULT 'ACTIVO',motivo_anulacion VARCHAR(500) NULL,created_by INT UNSIGNED NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(id_cliente) REFERENCES cliente(id_cliente),FOREIGN KEY(id_servicio) REFERENCES servicio(id_servicio),FOREIGN KEY(id_responsable) REFERENCES personal(id_personal)) ENGINE=InnoDB;
CREATE TABLE contrato_integrante (id_contrato INT UNSIGNED NOT NULL,id_cliente INT UNSIGNED NOT NULL,PRIMARY KEY(id_contrato,id_cliente),FOREIGN KEY(id_contrato) REFERENCES contrato(id_contrato),FOREIGN KEY(id_cliente) REFERENCES cliente(id_cliente)) ENGINE=InnoDB;
CREATE TABLE contrato_hito (id_hito INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,id_contrato INT UNSIGNED NOT NULL,numero SMALLINT UNSIGNED NOT NULL,descripcion VARCHAR(180) NOT NULL,fecha_vencimiento DATE NOT NULL,monto DECIMAL(12,2) NOT NULL,monto_pagado DECIMAL(12,2) NOT NULL DEFAULT 0,estado ENUM('PENDIENTE','PARCIAL','PAGADO','VENCIDO','ANULADO') NOT NULL DEFAULT 'PENDIENTE',UNIQUE KEY uq_hito(id_contrato,numero),FOREIGN KEY(id_contrato) REFERENCES contrato(id_contrato)) ENGINE=InnoDB;
CREATE TABLE cobranza (id_cobranza INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,id_contrato INT UNSIGNED NOT NULL,id_registrado_por INT UNSIGNED NOT NULL,fecha DATETIME NOT NULL,medio_pago VARCHAR(60) NOT NULL,numero_operacion VARCHAR(100) NULL,monto_total DECIMAL(12,2) NOT NULL,estado ENUM('REGISTRADO','ANULADO') NOT NULL DEFAULT 'REGISTRADO',motivo_anulacion VARCHAR(500) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(id_contrato) REFERENCES contrato(id_contrato),FOREIGN KEY(id_registrado_por) REFERENCES personal(id_personal),KEY ix_cobranza(fecha,estado)) ENGINE=InnoDB;
CREATE TABLE cobranza_detalle (id_cobranza INT UNSIGNED NOT NULL,id_hito INT UNSIGNED NOT NULL,monto_aplicado DECIMAL(12,2) NOT NULL,PRIMARY KEY(id_cobranza,id_hito),FOREIGN KEY(id_cobranza) REFERENCES cobranza(id_cobranza),FOREIGN KEY(id_hito) REFERENCES contrato_hito(id_hito)) ENGINE=InnoDB;
CREATE TABLE voucher (id_voucher INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,id_cobranza INT UNSIGNED NOT NULL,nombre_interno VARCHAR(80) NOT NULL UNIQUE,mime VARCHAR(80) NOT NULL,tamano INT UNSIGNED NOT NULL,hash_sha256 CHAR(64) NOT NULL,estado ENUM('VALIDADO','RETIRADO') NOT NULL DEFAULT 'VALIDADO',created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(id_cobranza) REFERENCES cobranza(id_cobranza)) ENGINE=InnoDB;
CREATE TABLE egreso (id_egreso INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,fecha DATE NOT NULL,categoria VARCHAR(100) NOT NULL,beneficiario VARCHAR(160) NOT NULL,concepto VARCHAR(500) NOT NULL,monto DECIMAL(12,2) NOT NULL,id_registrado_por INT UNSIGNED NOT NULL,estado ENUM('REGISTRADO','ANULADO') NOT NULL DEFAULT 'REGISTRADO',motivo_anulacion VARCHAR(500) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(id_registrado_por) REFERENCES personal(id_personal),KEY ix_egreso(fecha,estado)) ENGINE=InnoDB;
CREATE TABLE login_intento (id_login BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,usuario VARCHAR(80) NOT NULL,exitoso TINYINT NOT NULL,ip VARCHAR(45) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY ix_login(usuario,created_at)) ENGINE=InnoDB;
CREATE TABLE auditoria (id_auditoria BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,accion VARCHAR(60) NOT NULL,id_usuario INT UNSIGNED NULL,entidad VARCHAR(80) NOT NULL,id_registro INT UNSIGNED NOT NULL,datos_antes JSON NULL,datos_despues JSON NULL,ip VARCHAR(45) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY ix_audit(created_at),KEY ix_entidad(entidad,id_registro)) ENGINE=InnoDB;

INSERT INTO modulo(codigo,nombre) VALUES ('dashboard','Dashboard de ventas'),('clientes','Clientes'),('servicios','Servicios'),('contratos','Contratos'),('cobranzas','Cobranzas'),('egresos','Egresos'),('personal','Personal'),('cargos','Cargos'),('usuarios','Usuarios'),('auditoria','Auditoría') ON DUPLICATE KEY UPDATE nombre=VALUES(nombre);
INSERT IGNORE INTO permiso(id_modulo,accion) SELECT m.id_modulo,a.accion FROM modulo m CROSS JOIN (SELECT 'ver' accion UNION SELECT 'crear' UNION SELECT 'editar' UNION SELECT 'anular' UNION SELECT 'administrar') a;

DELIMITER $$
CREATE PROCEDURE sp_login_obtener_hash(IN p_usuario VARCHAR(80)) BEGIN SELECT u.id_usuario,u.id_personal,u.usu_nombre,u.password_hash,u.usu_estado,u.locked_until,CONCAT(p.nombres,' ',p.apellidos) nombre_completo FROM usuario u JOIN personal p ON p.id_personal=u.id_personal WHERE u.usu_nombre=p_usuario AND p.estado=1 LIMIT 1; END$$
CREATE PROCEDURE sp_login_registrar_intento(IN p_usuario VARCHAR(80),IN p_exitoso TINYINT) BEGIN DECLARE v_intentos TINYINT UNSIGNED DEFAULT 0; DECLARE v_inicio DATETIME; INSERT INTO login_intento(usuario,exitoso) VALUES(p_usuario,p_exitoso); IF p_exitoso=1 THEN UPDATE usuario SET failed_attempts=0,failed_window_started=NULL,locked_until=NULL,ultimo_login=NOW() WHERE usu_nombre=p_usuario; ELSE SELECT failed_attempts,failed_window_started INTO v_intentos,v_inicio FROM usuario WHERE usu_nombre=p_usuario FOR UPDATE; IF v_inicio IS NULL OR v_inicio<DATE_SUB(NOW(),INTERVAL 15 MINUTE) THEN SET v_intentos=1; SET v_inicio=NOW(); ELSE SET v_intentos=v_intentos+1; END IF; UPDATE usuario SET failed_attempts=v_intentos,failed_window_started=v_inicio,locked_until=IF(v_intentos>=5,DATE_ADD(NOW(),INTERVAL 15 MINUTE),NULL) WHERE usu_nombre=p_usuario; END IF; END$$
CREATE PROCEDURE sp_admin_inicializar(IN p_usuario VARCHAR(80),IN p_hash VARCHAR(255),IN p_nombres VARCHAR(120),IN p_apellidos VARCHAR(120),IN p_dni CHAR(8)) BEGIN DECLARE v_cargo INT UNSIGNED; DECLARE v_personal INT UNSIGNED; IF EXISTS(SELECT 1 FROM usuario u JOIN personal p ON p.id_personal=u.id_personal JOIN cargo c ON c.id_cargo=p.id_cargo WHERE c.nombre='Administrador') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Ya existe un administrador.'; END IF; START TRANSACTION; INSERT INTO cargo(nombre) VALUES('Administrador') ON DUPLICATE KEY UPDATE estado=1; SELECT id_cargo INTO v_cargo FROM cargo WHERE nombre='Administrador'; INSERT INTO cargo_permiso(id_cargo,id_permiso,permitido) SELECT v_cargo,id_permiso,1 FROM permiso ON DUPLICATE KEY UPDATE permitido=1; INSERT INTO personal(dni,nombres,apellidos,id_cargo) VALUES(p_dni,p_nombres,p_apellidos,v_cargo); SET v_personal=LAST_INSERT_ID(); INSERT INTO usuario(id_personal,usu_nombre,password_hash) VALUES(v_personal,p_usuario,p_hash); COMMIT; SELECT 1 resultado,'Administrador inicializado.' mensaje,v_personal id_personal; END$$
CREATE PROCEDURE sp_permiso_efectivo_listar(IN p_personal INT UNSIGNED) BEGIN SELECT m.codigo modulo,pr.accion,cp.permitido,'CARGO' origen FROM personal pe JOIN cargo_permiso cp ON cp.id_cargo=pe.id_cargo JOIN permiso pr ON pr.id_permiso=cp.id_permiso JOIN modulo m ON m.id_modulo=pr.id_modulo WHERE pe.id_personal=p_personal UNION ALL SELECT m.codigo,pr.accion,pp.permitido,'PERSONA' FROM persona_permiso pp JOIN permiso pr ON pr.id_permiso=pp.id_permiso JOIN modulo m ON m.id_modulo=pr.id_modulo WHERE pp.id_personal=p_personal; END$$
CREATE PROCEDURE sp_auditoria_registrar(IN p_accion VARCHAR(60),IN p_usuario INT UNSIGNED,IN p_id INT UNSIGNED,IN p_entidad VARCHAR(80),IN p_antes JSON,IN p_despues JSON,IN p_ip VARCHAR(45)) BEGIN INSERT INTO auditoria(accion,id_usuario,entidad,id_registro,datos_antes,datos_despues,ip) VALUES(p_accion,p_usuario,p_entidad,p_id,p_antes,p_despues,p_ip); END$$
CREATE PROCEDURE sp_auditoria_listar(IN p_inicio VARCHAR(10),IN p_fin VARCHAR(10),IN p_buscar VARCHAR(100)) BEGIN SELECT a.*,u.usu_nombre FROM auditoria a LEFT JOIN usuario u ON u.id_usuario=a.id_usuario WHERE(p_inicio='' OR DATE(a.created_at)>=p_inicio) AND(p_fin='' OR DATE(a.created_at)<=p_fin) AND(p_buscar='' OR a.entidad LIKE CONCAT('%',p_buscar,'%') OR a.accion LIKE CONCAT('%',p_buscar,'%')) ORDER BY a.id_auditoria DESC LIMIT 500; END$$
CREATE PROCEDURE sp_cargo_guardar(IN p_id INT UNSIGNED,IN p_nombre VARCHAR(100),IN p_estado TINYINT) BEGIN IF p_id=0 THEN INSERT INTO cargo(nombre,estado) VALUES(p_nombre,p_estado); SET p_id=LAST_INSERT_ID(); ELSE UPDATE cargo SET nombre=p_nombre,estado=p_estado WHERE id_cargo=p_id; END IF; SELECT 1 resultado,'Cargo guardado.' mensaje,p_id id_cargo; END$$
CREATE PROCEDURE sp_cargo_listar() BEGIN SELECT * FROM cargo ORDER BY nombre; END$$
CREATE PROCEDURE sp_personal_guardar(IN p_id INT UNSIGNED,IN p_dni CHAR(8),IN p_nombres VARCHAR(120),IN p_apellidos VARCHAR(120),IN p_correo VARCHAR(160),IN p_telefono VARCHAR(30),IN p_cargo INT UNSIGNED,IN p_estado TINYINT) BEGIN IF p_id=0 THEN INSERT INTO personal(dni,nombres,apellidos,correo,telefono,id_cargo,estado) VALUES(p_dni,p_nombres,p_apellidos,NULLIF(p_correo,''),NULLIF(p_telefono,''),p_cargo,p_estado); SET p_id=LAST_INSERT_ID(); ELSE UPDATE personal SET dni=p_dni,nombres=p_nombres,apellidos=p_apellidos,correo=NULLIF(p_correo,''),telefono=NULLIF(p_telefono,''),id_cargo=p_cargo,estado=p_estado WHERE id_personal=p_id; END IF; SELECT 1 resultado,'Personal guardado.' mensaje,p_id id_personal; END$$
CREATE PROCEDURE sp_personal_listar() BEGIN SELECT p.*,c.nombre cargo,u.id_usuario,u.usu_nombre,u.usu_estado FROM personal p JOIN cargo c ON c.id_cargo=p.id_cargo LEFT JOIN usuario u ON u.id_personal=p.id_personal ORDER BY p.apellidos,p.nombres; END$$
CREATE PROCEDURE sp_usuario_guardar(IN p_id INT UNSIGNED,IN p_personal INT UNSIGNED,IN p_nombre VARCHAR(80),IN p_hash VARCHAR(255),IN p_estado TINYINT) BEGIN IF p_id=0 THEN INSERT INTO usuario(id_personal,usu_nombre,password_hash,usu_estado) VALUES(p_personal,p_nombre,p_hash,p_estado); ELSE UPDATE usuario SET usu_nombre=p_nombre,usu_estado=p_estado,password_hash=IF(p_hash='',password_hash,p_hash) WHERE id_usuario=p_id; END IF; SELECT 1 resultado,'Usuario guardado.' mensaje,IF(p_id=0,LAST_INSERT_ID(),p_id) id_usuario; END$$
CREATE PROCEDURE sp_persona_permiso_guardar(IN p_personal INT UNSIGNED,IN p_permiso INT UNSIGNED,IN p_permitido TINYINT) BEGIN INSERT INTO persona_permiso VALUES(p_personal,p_permiso,p_permitido) ON DUPLICATE KEY UPDATE permitido=p_permitido; SELECT 1 resultado,'Permiso individual guardado.' mensaje; END$$
CREATE PROCEDURE sp_cargo_permiso_guardar(IN p_cargo INT UNSIGNED,IN p_permiso INT UNSIGNED,IN p_permitido TINYINT) BEGIN INSERT INTO cargo_permiso VALUES(p_cargo,p_permiso,p_permitido) ON DUPLICATE KEY UPDATE permitido=p_permitido; SELECT 1 resultado,'Permiso de cargo guardado.' mensaje; END$$
CREATE PROCEDURE sp_permiso_listar() BEGIN SELECT pr.id_permiso,m.codigo modulo,pr.accion FROM permiso pr JOIN modulo m ON m.id_modulo=pr.id_modulo ORDER BY m.nombre,pr.accion; END$$
CREATE PROCEDURE sp_cargo_permiso_configuracion_listar(IN p_cargo INT UNSIGNED) BEGIN SELECT pr.id_permiso,m.codigo modulo,pr.accion,cp.permitido plantilla FROM permiso pr JOIN modulo m ON m.id_modulo=pr.id_modulo LEFT JOIN cargo_permiso cp ON cp.id_permiso=pr.id_permiso AND cp.id_cargo=p_cargo ORDER BY m.nombre,pr.accion; END$$
CREATE PROCEDURE sp_persona_permiso_configuracion_listar(IN p_persona INT UNSIGNED) BEGIN SELECT pr.id_permiso,m.codigo modulo,pr.accion,cp.permitido plantilla,pp.permitido excepcion,COALESCE(pp.permitido,cp.permitido,0) efectivo FROM personal pe CROSS JOIN permiso pr JOIN modulo m ON m.id_modulo=pr.id_modulo LEFT JOIN cargo_permiso cp ON cp.id_cargo=pe.id_cargo AND cp.id_permiso=pr.id_permiso LEFT JOIN persona_permiso pp ON pp.id_personal=pe.id_personal AND pp.id_permiso=pr.id_permiso WHERE pe.id_personal=p_persona ORDER BY m.nombre,pr.accion; END$$
CREATE PROCEDURE sp_persona_permiso_quitar(IN p_persona INT UNSIGNED,IN p_permiso INT UNSIGNED) BEGIN DELETE FROM persona_permiso WHERE id_personal=p_persona AND id_permiso=p_permiso; SELECT 1 resultado,'Excepción retirada; se aplica la plantilla del cargo.' mensaje; END$$
CREATE PROCEDURE sp_cliente_listar() BEGIN SELECT * FROM cliente ORDER BY id_cliente DESC; END$$
CREATE PROCEDURE sp_cliente_guardar(IN p_id INT UNSIGNED,IN p_tipo VARCHAR(10),IN p_doc VARCHAR(11),IN p_nombres VARCHAR(150),IN p_apellidos VARCHAR(150),IN p_razon VARCHAR(180),IN p_correo VARCHAR(160),IN p_telefono VARCHAR(30),IN p_direccion VARCHAR(220),IN p_estado TINYINT) BEGIN IF p_id=0 THEN INSERT INTO cliente(tipo,documento,nombres,apellidos,razon_social,correo,telefono,direccion,estado) VALUES(p_tipo,p_doc,NULLIF(p_nombres,''),NULLIF(p_apellidos,''),NULLIF(p_razon,''),NULLIF(p_correo,''),NULLIF(p_telefono,''),NULLIF(p_direccion,''),p_estado); SET p_id=LAST_INSERT_ID(); ELSE UPDATE cliente SET tipo=p_tipo,documento=p_doc,nombres=NULLIF(p_nombres,''),apellidos=NULLIF(p_apellidos,''),razon_social=NULLIF(p_razon,''),correo=NULLIF(p_correo,''),telefono=NULLIF(p_telefono,''),direccion=NULLIF(p_direccion,''),estado=p_estado WHERE id_cliente=p_id; END IF; SELECT 1 resultado,'Cliente guardado.' mensaje,p_id id_cliente; END$$
CREATE PROCEDURE sp_cliente_buscar(IN p_consulta VARCHAR(100)) BEGIN SELECT id_cliente,tipo,documento,nombres,apellidos,razon_social,estado FROM cliente WHERE estado=1 AND (documento LIKE CONCAT('%',p_consulta,'%') OR nombres LIKE CONCAT('%',p_consulta,'%') OR apellidos LIKE CONCAT('%',p_consulta,'%') OR CONCAT_WS(' ',nombres,apellidos) LIKE CONCAT('%',p_consulta,'%') OR razon_social LIKE CONCAT('%',p_consulta,'%')) ORDER BY CASE WHEN documento=p_consulta THEN 0 ELSE 1 END,documento LIMIT 20; END$$
CREATE PROCEDURE sp_servicio_listar() BEGIN SELECT * FROM servicio ORDER BY nombre; END$$
CREATE PROCEDURE sp_servicio_guardar(IN p_id INT UNSIGNED,IN p_nombre VARCHAR(150),IN p_descripcion VARCHAR(500),IN p_precio DECIMAL(12,2),IN p_estado TINYINT) BEGIN IF p_id=0 THEN INSERT INTO servicio(nombre,descripcion,precio_referencia,estado) VALUES(p_nombre,NULLIF(p_descripcion,''),p_precio,p_estado); SET p_id=LAST_INSERT_ID(); ELSE UPDATE servicio SET nombre=p_nombre,descripcion=NULLIF(p_descripcion,''),precio_referencia=p_precio,estado=p_estado WHERE id_servicio=p_id; END IF; SELECT 1 resultado,'Servicio guardado.' mensaje,p_id id_servicio; END$$
CREATE PROCEDURE sp_contrato_crear(IN p_cliente INT UNSIGNED,IN p_servicio INT UNSIGNED,IN p_responsable INT UNSIGNED,IN p_tipo VARCHAR(12),IN p_fecha DATE,IN p_bruto DECIMAL(12,2),IN p_descuento DECIMAL(12,2),IN p_usuario INT UNSIGNED) BEGIN DECLARE v_numero VARCHAR(30); DECLARE v_siguiente INT; SELECT COUNT(*)+1 INTO v_siguiente FROM contrato WHERE YEAR(fecha)=YEAR(p_fecha); SET v_numero=CONCAT('TES-',YEAR(p_fecha),'-',LPAD(v_siguiente,6,'0')); INSERT INTO contrato(con_numero,id_cliente,id_servicio,id_responsable,tipo,fecha,monto_bruto,descuento,monto_neto,created_by) VALUES(v_numero,p_cliente,p_servicio,p_responsable,p_tipo,p_fecha,p_bruto,p_descuento,p_bruto-p_descuento,p_usuario); SELECT 1 resultado,'Contrato registrado.' mensaje,LAST_INSERT_ID() id_contrato,v_numero con_numero; END$$
CREATE PROCEDURE sp_contrato_integrante_guardar(IN p_contrato INT UNSIGNED,IN p_cliente INT UNSIGNED) BEGIN IF NOT EXISTS(SELECT 1 FROM cliente WHERE id_cliente=p_cliente AND estado=1) THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El integrante no es un cliente activo.'; END IF; INSERT INTO contrato_integrante VALUES(p_contrato,p_cliente); END$$
CREATE PROCEDURE sp_contrato_hito_guardar(IN p_contrato INT UNSIGNED,IN p_numero SMALLINT,IN p_descripcion VARCHAR(180),IN p_fecha DATE,IN p_monto DECIMAL(12,2)) BEGIN IF p_monto<=0 OR p_fecha IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Cuota inválida.'; END IF; INSERT INTO contrato_hito(id_contrato,numero,descripcion,fecha_vencimiento,monto) VALUES(p_contrato,p_numero,p_descripcion,p_fecha,p_monto); END$$
CREATE PROCEDURE sp_contrato_hitos_validar(IN p_contrato INT UNSIGNED) BEGIN DECLARE v_neto DECIMAL(12,2); DECLARE v_total DECIMAL(12,2); SELECT monto_neto INTO v_neto FROM contrato WHERE id_contrato=p_contrato FOR UPDATE; SELECT COALESCE(SUM(monto),0) INTO v_total FROM contrato_hito WHERE id_contrato=p_contrato; IF v_neto IS NULL OR ABS(v_neto-v_total)>0.001 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Las cuotas no coinciden con el monto neto.'; END IF; END$$
CREATE PROCEDURE sp_contrato_listar() BEGIN SELECT c.*,COALESCE(SUM(h.monto-h.monto_pagado),0) saldo,COALESCE(cl.razon_social,CONCAT_WS(' ',cl.nombres,cl.apellidos)) cliente_nombre,s.nombre servicio_nombre FROM contrato c JOIN cliente cl ON cl.id_cliente=c.id_cliente JOIN servicio s ON s.id_servicio=c.id_servicio LEFT JOIN contrato_hito h ON h.id_contrato=c.id_contrato AND h.estado<>'ANULADO' GROUP BY c.id_contrato ORDER BY c.id_contrato DESC; END$$
CREATE PROCEDURE sp_contrato_detalle(IN p_contrato INT UNSIGNED) BEGIN SELECT * FROM contrato WHERE id_contrato=p_contrato; SELECT * FROM contrato_hito WHERE id_contrato=p_contrato ORDER BY numero; SELECT cl.* FROM contrato_integrante ci JOIN cliente cl ON cl.id_cliente=ci.id_cliente WHERE ci.id_contrato=p_contrato; END$$
CREATE PROCEDURE sp_contrato_anular(IN p_contrato INT UNSIGNED,IN p_motivo VARCHAR(500)) BEGIN IF CHAR_LENGTH(TRIM(p_motivo))=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El motivo de anulación es obligatorio.'; END IF; IF EXISTS(SELECT 1 FROM cobranza WHERE id_contrato=p_contrato AND estado='REGISTRADO') THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='No puede anular un contrato con cobranzas activas.'; END IF; UPDATE contrato SET estado='ANULADO',motivo_anulacion=p_motivo WHERE id_contrato=p_contrato AND estado<>'ANULADO'; IF ROW_COUNT()=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Contrato no disponible para anulación.'; END IF; UPDATE contrato_hito SET estado='ANULADO' WHERE id_contrato=p_contrato; SELECT 1 resultado,'Contrato anulado.' mensaje; END$$
CREATE PROCEDURE sp_cobranza_registrar(IN p_contrato INT UNSIGNED,IN p_personal INT UNSIGNED,IN p_fecha DATETIME,IN p_medio VARCHAR(60),IN p_operacion VARCHAR(100),IN p_detalles JSON,IN p_voucher_nombre VARCHAR(80),IN p_voucher_mime VARCHAR(80),IN p_voucher_tamano INT,IN p_voucher_hash CHAR(64)) BEGIN DECLARE v_i INT DEFAULT 0; DECLARE v_total DECIMAL(12,2) DEFAULT 0; DECLARE v_hito INT UNSIGNED; DECLARE v_monto DECIMAL(12,2); DECLARE v_saldo DECIMAL(12,2); DECLARE v_cobranza INT UNSIGNED; DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END; IF JSON_LENGTH(p_detalles)=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Debe aplicar el pago a una cuota.'; END IF; START TRANSACTION; WHILE v_i<JSON_LENGTH(p_detalles) DO SET v_hito=CAST(JSON_UNQUOTE(JSON_EXTRACT(p_detalles,CONCAT('$[',v_i,'].id_hito'))) AS UNSIGNED); SET v_monto=CAST(JSON_UNQUOTE(JSON_EXTRACT(p_detalles,CONCAT('$[',v_i,'].monto'))) AS DECIMAL(12,2)); SELECT monto-monto_pagado INTO v_saldo FROM contrato_hito WHERE id_hito=v_hito AND id_contrato=p_contrato AND estado IN('PENDIENTE','PARCIAL') FOR UPDATE; IF v_monto<=0 OR v_saldo IS NULL OR v_monto>v_saldo THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El pago supera el saldo de una cuota.'; END IF; SET v_total=v_total+v_monto; SET v_i=v_i+1; END WHILE; INSERT INTO cobranza(id_contrato,id_registrado_por,fecha,medio_pago,numero_operacion,monto_total) VALUES(p_contrato,p_personal,p_fecha,p_medio,NULLIF(p_operacion,''),v_total); SET v_cobranza=LAST_INSERT_ID(); SET v_i=0; WHILE v_i<JSON_LENGTH(p_detalles) DO SET v_hito=CAST(JSON_UNQUOTE(JSON_EXTRACT(p_detalles,CONCAT('$[',v_i,'].id_hito'))) AS UNSIGNED); SET v_monto=CAST(JSON_UNQUOTE(JSON_EXTRACT(p_detalles,CONCAT('$[',v_i,'].monto'))) AS DECIMAL(12,2)); INSERT INTO cobranza_detalle VALUES(v_cobranza,v_hito,v_monto); UPDATE contrato_hito SET monto_pagado=monto_pagado+v_monto,estado=IF(monto_pagado+v_monto>=monto,'PAGADO','PARCIAL') WHERE id_hito=v_hito; SET v_i=v_i+1; END WHILE; IF p_voucher_nombre<>'' THEN INSERT INTO voucher(id_cobranza,nombre_interno,mime,tamano,hash_sha256) VALUES(v_cobranza,p_voucher_nombre,p_voucher_mime,p_voucher_tamano,p_voucher_hash); END IF; IF NOT EXISTS(SELECT 1 FROM contrato_hito WHERE id_contrato=p_contrato AND estado IN('PENDIENTE','PARCIAL','VENCIDO')) THEN UPDATE contrato SET estado='FINALIZADO' WHERE id_contrato=p_contrato; END IF; COMMIT; SELECT 1 resultado,'Cobranza registrada.' mensaje,v_cobranza id_cobranza; END$$
CREATE PROCEDURE sp_cobranza_anular(IN p_cobranza INT UNSIGNED,IN p_motivo VARCHAR(500)) BEGIN DECLARE v_contrato INT UNSIGNED; DECLARE EXIT HANDLER FOR SQLEXCEPTION BEGIN ROLLBACK; RESIGNAL; END; IF CHAR_LENGTH(TRIM(p_motivo))=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El motivo de anulación es obligatorio.'; END IF; START TRANSACTION; SELECT id_contrato INTO v_contrato FROM cobranza WHERE id_cobranza=p_cobranza AND estado='REGISTRADO' FOR UPDATE; IF v_contrato IS NULL THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Cobranza no disponible para anulación.'; END IF; UPDATE cobranza SET estado='ANULADO',motivo_anulacion=p_motivo WHERE id_cobranza=p_cobranza AND estado='REGISTRADO'; IF ROW_COUNT()<>1 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Cobranza no disponible para anulación.'; END IF; UPDATE contrato_hito h JOIN(SELECT id_hito,SUM(monto_aplicado) monto FROM cobranza_detalle WHERE id_cobranza=p_cobranza GROUP BY id_hito)d ON d.id_hito=h.id_hito SET h.monto_pagado=GREATEST(0,h.monto_pagado-d.monto),h.estado=IF(GREATEST(0,h.monto_pagado-d.monto)=0,'PENDIENTE','PARCIAL'); UPDATE contrato SET estado='ACTIVO' WHERE id_contrato=v_contrato AND estado='FINALIZADO'; COMMIT; SELECT 1 resultado,'Cobranza anulada y cuotas revertidas.' mensaje; END$$
CREATE PROCEDURE sp_cobranza_listar(IN p_inicio VARCHAR(10),IN p_fin VARCHAR(10),IN p_estado VARCHAR(15)) BEGIN SELECT c.*,co.con_numero FROM cobranza c JOIN contrato co ON co.id_contrato=c.id_contrato WHERE(p_inicio='' OR DATE(c.fecha)>=p_inicio) AND(p_fin='' OR DATE(c.fecha)<=p_fin) AND(p_estado='' OR c.estado=p_estado) ORDER BY c.id_cobranza DESC; END$$
CREATE PROCEDURE sp_hitos_cobranza_listar(IN p_contrato INT UNSIGNED) BEGIN SELECT *,monto-monto_pagado saldo FROM contrato_hito WHERE id_contrato=p_contrato AND estado IN('PENDIENTE','PARCIAL','VENCIDO') ORDER BY numero; END$$
CREATE PROCEDURE sp_dashboard_ventas_resumen(IN p_desde DATE,IN p_hasta DATE) BEGIN DECLARE v_cobrado DECIMAL(12,2) DEFAULT 0; DECLARE v_pendiente DECIMAL(12,2) DEFAULT 0; DECLARE v_activos INT DEFAULT 0; SELECT COALESCE(SUM(monto_total),0) INTO v_cobrado FROM cobranza WHERE estado='REGISTRADO' AND DATE(fecha) BETWEEN p_desde AND p_hasta; SELECT COALESCE(SUM(h.monto-h.monto_pagado),0) INTO v_pendiente FROM contrato_hito h JOIN contrato c ON c.id_contrato=h.id_contrato WHERE c.estado IN('ACTIVO','FINALIZADO') AND h.estado IN('PENDIENTE','PARCIAL','VENCIDO'); SELECT COUNT(*) INTO v_activos FROM contrato WHERE estado='ACTIVO'; SELECT v_cobrado cobrado,v_pendiente por_cobrar,v_activos contratos_activos,ROUND(IFNULL(v_cobrado/NULLIF(v_cobrado+v_pendiente,0)*100,0),2) efectividad; END$$
CREATE PROCEDURE sp_dashboard_ventas_evolucion(IN p_desde DATE,IN p_hasta DATE) BEGIN SELECT DATE(fecha) fecha,COALESCE(SUM(monto_total),0) cobrado FROM cobranza WHERE estado='REGISTRADO' AND DATE(fecha) BETWEEN p_desde AND p_hasta GROUP BY DATE(fecha) ORDER BY fecha; END$$
CREATE PROCEDURE sp_dashboard_ventas_embudo(IN p_desde DATE,IN p_hasta DATE) BEGIN SELECT h.estado,COUNT(*) cantidad,COALESCE(SUM(h.monto-h.monto_pagado),0) monto FROM contrato_hito h JOIN contrato c ON c.id_contrato=h.id_contrato WHERE c.estado<>'ANULADO' AND h.fecha_vencimiento BETWEEN p_desde AND p_hasta GROUP BY h.estado ORDER BY FIELD(h.estado,'PENDIENTE','PARCIAL','VENCIDO','PAGADO'); END$$
CREATE PROCEDURE sp_dashboard_ventas_servicios(IN p_desde DATE,IN p_hasta DATE) BEGIN SELECT s.nombre,COALESCE(SUM(c.monto_neto),0) contratado,COALESCE((SELECT SUM(co.monto_total) FROM cobranza co JOIN contrato cx ON cx.id_contrato=co.id_contrato WHERE co.estado='REGISTRADO' AND cx.id_servicio=s.id_servicio AND DATE(co.fecha) BETWEEN p_desde AND p_hasta),0) cobrado FROM servicio s LEFT JOIN contrato c ON c.id_servicio=s.id_servicio AND c.estado<>'ANULADO' AND c.fecha BETWEEN p_desde AND p_hasta GROUP BY s.id_servicio,s.nombre HAVING contratado>0 OR cobrado>0 ORDER BY contratado DESC,s.nombre LIMIT 8; END$$
CREATE PROCEDURE sp_dashboard_ventas_pendientes(IN p_desde DATE,IN p_hasta DATE) BEGIN SELECT h.id_hito,c.con_numero,COALESCE(cl.razon_social,CONCAT_WS(' ',cl.nombres,cl.apellidos)) cliente,h.descripcion,h.fecha_vencimiento,h.monto-h.monto_pagado saldo,h.estado FROM contrato_hito h JOIN contrato c ON c.id_contrato=h.id_contrato JOIN cliente cl ON cl.id_cliente=c.id_cliente WHERE c.estado='ACTIVO' AND h.estado IN('PENDIENTE','PARCIAL','VENCIDO') AND h.fecha_vencimiento BETWEEN p_desde AND p_hasta ORDER BY h.fecha_vencimiento,h.id_hito LIMIT 30; END$$
CREATE PROCEDURE sp_voucher_registrar(IN p_cobranza INT UNSIGNED,IN p_nombre VARCHAR(80),IN p_mime VARCHAR(80),IN p_tamano INT,IN p_hash CHAR(64)) BEGIN INSERT INTO voucher(id_cobranza,nombre_interno,mime,tamano,hash_sha256) VALUES(p_cobranza,p_nombre,p_mime,p_tamano,p_hash); SELECT 1 resultado,'Voucher registrado.' mensaje,LAST_INSERT_ID() id_voucher; END$$
CREATE PROCEDURE sp_voucher_obtener(IN p_voucher INT UNSIGNED) BEGIN SELECT * FROM voucher WHERE id_voucher=p_voucher AND estado='VALIDADO'; END$$
CREATE PROCEDURE sp_egreso_registrar(IN p_fecha DATE,IN p_categoria VARCHAR(100),IN p_beneficiario VARCHAR(160),IN p_concepto VARCHAR(500),IN p_monto DECIMAL(12,2),IN p_personal INT UNSIGNED) BEGIN INSERT INTO egreso(fecha,categoria,beneficiario,concepto,monto,id_registrado_por) VALUES(p_fecha,p_categoria,p_beneficiario,p_concepto,p_monto,p_personal); SELECT 1 resultado,'Egreso registrado.' mensaje,LAST_INSERT_ID() id_egreso; END$$
CREATE PROCEDURE sp_egreso_listar(IN p_inicio VARCHAR(10),IN p_fin VARCHAR(10),IN p_estado VARCHAR(15)) BEGIN SELECT * FROM egreso WHERE(p_inicio='' OR fecha>=p_inicio) AND(p_fin='' OR fecha<=p_fin) AND(p_estado='' OR estado=p_estado) ORDER BY fecha DESC,id_egreso DESC; END$$
CREATE PROCEDURE sp_egreso_anular(IN p_egreso INT UNSIGNED,IN p_motivo VARCHAR(500)) BEGIN IF CHAR_LENGTH(TRIM(p_motivo))=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='El motivo de anulación es obligatorio.'; END IF; UPDATE egreso SET estado='ANULADO',motivo_anulacion=p_motivo WHERE id_egreso=p_egreso AND estado='REGISTRADO'; IF ROW_COUNT()=0 THEN SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Egreso no disponible para anulación.'; END IF; SELECT 1 resultado,'Egreso anulado.' mensaje; END$$
DELIMITER ;
